import { ColSpecs } from '@models/specs/col-specs';
export interface BaseCardInfo extends ColSpecs {
    id?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    dateCreated?: string;
    status?: string;
    lastUpdatedVal?: number;
    lastUpdated?: string;
    createdDate?: string;
    siDateCreated?: string;
    needType?: string;
    product?: string;
    applicationNumber?: string;
    attachedDate?: string;
    policyNumber?: string;
    type?: string;
    signatureNumber?: string;
    personId?: string;
    
    phoneNumber?: any;
    accountManagerId?: any;
    emailAddress?: any;
    hasConsent?: any;
    isDeleted?: any;
    syncStatus?: any;
    occupation?: any;
    monthlyIncome?: any;
    householdIncome?: any;
    homeBuildingName?: any;
    homeBlockNumber?: any;
    homeStreet?: any;
    homeCityCode?: any;
    homeCountryCode?: any;
    homeState?: any;
    homeZipCode?: any;
    homeSubDivision?: any;
    homeProvinceCode?: any;
    workBuildingName?: any;
    workBlockNumber?: any;
    workStreet?: any;
    workCityCode?: any;
    workCountryCode?: any;
    workZipCode?: any;
    workSubDivision?: any;
    workProvinceCode?: any;
    workState?: any;
    savingsPriority?: any;
    healthPriority?: any;
    protectionPriority?: any;
    educationPriority?: any;
    retirementPriority?: any;
    estatePlanningPriority?: any;
    dateOfBirth?: any;
    gender?: any;
    civilStatus?:any;
    incomeRange?: any;
    dateModified?: any;
    serverId?: any;
    proposalAge?: any;
    goalType?: any;
    isWaived?: any;
    leadServerId?: any;
    naServerId?: any;
    leadStatusDetail?: any;
    occupationCode?: any;
    occupationTitle?: any;
    planType?: string;
    isDisabled?: boolean;
    insuredName?: string;
    isCompleted?: any;
    irpqAns?: any[];
    fnaIsWaived?: any;

    leadId?: string;
    naId?: any;
    irpqId?: string;
    siId?: string;
    eappId?: string;
    submissionId?: string;

    leadStatus?: string;
    fnaStatus?: string;
    irpqStatus?: string;
    siStatus?: string; 
    eappStatus?: string;
    submissionStatus?: string;

    leadSyncStatus?: any;
    fnaSyncStatus?: any;
    irpqSyncStatus?: any;
    siSyncStatus?: any;
    eappSyncStatus?: any;
    submissionSyncStatus?: any;

    syncCountStatus?: number;

    isSelected?: boolean;
    generatedOnline?: boolean;
    isSignatureEdited?: boolean;
}
