export const CONSTANT_DB_TABLE = {
  LEADS: 'Leads',
  REFERROR: 'Referrors',
  NEED_ANALYSIS: 'FNA_MAIN',
  IRPQ: 'Irpq',
  SI_MAIN: 'SI_MAIN',
  SI_PERSONS: 'SI_PERSONS',
  SI_TOPUP: 'SI_TOPUP',
  SI_RIDERS: 'SI_RIDERS',
  SI_FUNDS: 'SI_FUNDS',
  EAPP_MAIN: 'EAPP_Main',
  EAPP_PERSON: 'EAPP_Person',
  EAPP_PERSON_VESSEL: 'EAPP_Person_VesselOperationInfo',
  EAPP_BENE: 'EAPP_Beneficiaries',
  EAPP_FUNDS: 'EAPP_FundsTopUpDirection',
  EAPP_PAYOUT_BANKS: 'EAPP_Payout_Banks',
  EAPP_PENDING_APP: 'EAPP_PendingApplication',
  EAPP_TOTAL_INSURANCE: 'EAPP_TotalInsuranceInforce',
  EAPP_REP_NOTIF: 'EAPP_ReplacementNotification',
  EAPP_NONMED_MAIN: 'EAPP_NonMed_Main',
  EAPP_NONMED_FAMILY: 'EAPP_NonMed_FamilyMembers',
  EAPP_NONMED_ADOC: 'EAPP_NonMed_Alcohol_Doctors',
  EAPP_NONMED_DDOC: 'EAPP_NonMed_Detox_Doctors',
  EAPP_NONMED_TRAVEL: 'EAPP_NonMed_Foreign_Travel_Residence',
  EAPP_NONMED_VESSEL: 'EAPP_NonMed_VesselOperationInfo',
  EAPP_NONMED_ANS: 'EAPP_NonMed_Answers',
  EAPP_BENFICIARY_OWNER: 'Beneficiary_Owners',
  SUBMISSION_ACR : 'Submission_ACR',
  SUBMISSION_ACB : 'Submission_ACB',
  SUBMISSION_ADA: 'Submission_ADA',
  SUBMISSION_CHECKLIST: 'Submission_Checklist',
  SUBMISSION_ATTACHMENTS: 'Submission_Attachments',
  SUBMISSION_EPAYMENT: 'Submission_EPayment',
  EAPP_SIGNATURES: 'EAPP_Signatures',
  BO: 'Beneficiary_Owners',
  DEPENDENTS: 'Dependents_Table'
};