export const PREMIUM_MAPPING = {
    UL_AZ_GENESIS_PHP_NG_HSBC: 'modalPremium',
    UL_AZ_GENESIS_USD_NG_HSBC: 'modalPremium',
    UL_AZ_PROSPERITY_PHP_GAE_HSBC: 'inputPremium',
    UL_AZ_PROSPERITY_USD_GAE_HSBC: 'inputPremium',
    TR_ACHIEVERS_PHP_NG_PNB: 'Achievers Version 2',
    TR_BIDA_10_PHP_NG_AGENCY: 'Bida! 10 Version 2',
    TR_BIDA_10_PHP_NG_PNB: 'Bida! 10 Version 2',
    TR_BIDA_15_PHP_NG_AGENCY: 'Bida! 15 Version 2',
    TR_BIDA_15_PHP_NG_PNB: 'Bida! 15 Version 2',
    TR_EAZY_HEALTH_1000_PHP_NG_AGENCY: 'premiumTotal',
    TR_EAZY_HEALTH_1000_PHP_NG_ALT: 'premiumTotal',
    TR_EAZY_HEALTH_1000_PHP_NG_HSBC: 'premiumTotal',
    TR_EAZY_HEALTH_1000_PHP_NG_PNB: 'premiumTotal',
    TR_EAZY_HEALTH_1000_PHP_NG_WST_LTG: 'premiumTotal',
    TR_EAZY_HEALTH_1500_PHP_NG_AGENCY: 'premiumTotal',
    TR_EAZY_HEALTH_1500_PHP_NG_ALT: 'premiumTotal',
    TR_EAZY_HEALTH_1500_PHP_NG_HSBC: 'premiumTotal',
    TR_EAZY_HEALTH_1500_PHP_NG_PNB: 'premiumTotal',
    TR_EAZY_HEALTH_1500_PHP_NG_WST_LTG: 'premiumTotal',
    TR_TERM10_PHP_NG_PNB: 'Renewable & Convertible Term 10-year',
    TR_TERM15_PHP_NG_PNB: 'Renewable & Convertible Term 15-year',
    TR_TERM1_PHP_NG_PNB: 'Renewable & Convertible Term 1-year',
    TR_TERM5_PHP_NG_PNB: 'Renewable & Convertible Term 5-year',
    UL_AZPIRE_GROWTH_PHP_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_GAE_PNB: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_GAE_WST_LTG: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_NG_HSBC: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_NG_PNB: 'modalPremium',
    UL_AZPIRE_GROWTH_PHP_NG_WST_LTG: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_GAE_PNB: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_GAE_WST_LTG: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_NG_HSBC: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_NG_PNB: 'modalPremium',
    UL_AZPIRE_GROWTH_USD_NG_WST_LTG: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_GAE_PNB: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_NG_HSBC: 'modalPremium',
    UL_AZPIRE_PEAK_PHP_NG_PNB: 'modalPremium',
    UL_DIVERSIFY_USD_NG_AGENCY: 'modalPremium',
    UL_DIVERSIFY_USD_NG_PNB: 'modalPremium',
    UL_HEALTH_10_PHP_NG_AGENCY: 'modalPremium',
    UL_HEALTH_10_PHP_NG_PNB: 'modalPremium',
    UL_HEALTH_10_USD_NG_AGENCY: 'modalPremium',
    UL_HEALTH_10_USD_NG_PNB: 'modalPremium',
    UL_HEALTH_20_PHP_NG_AGENCY: 'modalPremium',
    UL_HEALTH_20_PHP_NG_PNB: 'modalPremium',
    UL_HEALTH_20_USD_NG_AGENCY: 'modalPremium',
    UL_HEALTH_20_USD_NG_PNB: 'modalPremium',
    UL_HEALTH_PHP_NG_AGENCY: 'modalPremium',
    UL_HEALTH_PHP_NG_PNB: 'modalPremium',
    UL_HEALTH_USD_NG_AGENCY: 'modalPremium',
    UL_HEALTH_USD_NG_PNB: 'modalPremium',
    UL_MAXIMAL_PHP_NG_AGENCY: 'inputPremium',
    UL_MAXIMAL_PHP_NG_PNB: 'inputPremium',
    UL_MAXIMAL_USD_NG_AGENCY: 'inputPremium',
    UL_MAXIMAL_USD_NG_PNB: 'inputPremium',
    UL_OPTIMAL_PHP_NG_AGENCY: 'inputPremium',
    UL_OPTIMAL_PHP_NG_PNB: 'inputPremium',
    UL_OPTIMAL_USD_NG_AGENCY: 'inputPremium',
    UL_OPTIMAL_USD_NG_PNB: 'inputPremium',
    UL_OPTIMAX_PHP_GAE_PNB: 'inputPremium',
    UL_OPTIMAX_USD_GAE_PNB: 'inputPremium',
    UL_OPTIMAX_PHP_GAE_AGENCY: 'inputPremium',
    UL_OPTIMAX_USD_GAE_AGENCY: 'inputPremium',
    UL_OPTIMUM_PHP_GAE_AGENCY: 'inputPremium',
    UL_OPTIMUM_PHP_GAE_PNB: 'inputPremium',
    UL_OPTIMUM_USD_GAE_AGENCY: 'inputPremium',
    UL_OPTIMUM_USD_GAE_PNB: 'inputPremium',
    UL_AZPIRE_PEAK_USD_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_PEAK_USD_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_PEAK_USD_GAE_PNB: 'modalPremium',
    UL_AZPIRE_PEAK_USD_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_PEAK_USD_NG_HSBC: 'modalPremium',
    UL_AZPIRE_PEAK_USD_NG_PNB: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_GAE_PNB: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_NG_HSBC: 'modalPremium',
    UL_AZPIRE_WIZ_PHP_NG_PNB: 'modalPremium',
    UL_AZPIRE_WIZ_USD_GAE_AGENCY: 'modalPremium',
    UL_AZPIRE_WIZ_USD_GAE_HSBC: 'modalPremium',
    UL_AZPIRE_WIZ_USD_GAE_PNB: 'modalPremium',
    UL_AZPIRE_WIZ_USD_NG_AGENCY: 'modalPremium',
    UL_AZPIRE_WIZ_USD_NG_HSBC: 'modalPremium',
    UL_AZPIRE_WIZ_USD_NG_PNB: 'modalPremium',
    UL_DIVERSIFY_PHP_GAE_AGENCY: 'modalPremium',
    UL_DIVERSIFY_PHP_GAE_PNB: 'modalPremium',
    UL_DIVERSIFY_PHP_NG_AGENCY: 'modalPremium',
    UL_DIVERSIFY_PHP_NG_PNB: 'modalPremium',
    UL_DIVERSIFY_USD_GAE_AGENCY: 'modalPremium',
    UL_DIVERSIFY_USD_GAE_PNB: 'modalPremium',
    TR_INTENSIFY4_PHP_GAE_PNB: '4-Pay Peso Intensify! with GAE',
    TR_INTENSIFY4_PHP_NG_PNB: '4-Pay Peso Intensify!',
    TR_INTENSIFY6_PHP_GAE_PNB: '6-Pay Peso Intensify! with GAE',
    TR_INTENSIFY6_PHP_NG_PNB: '6-Pay Peso Intensify!',
    TR_INTENSIFY8_PHP_NG_PNB: '8-Pay Peso Intensify!',
    TR_PREMIER_LIFE10_PHP_NG_PNB: 'inputPremium',
    TR_PREMIER_LIFE_PHP_NG_PNB: 'Premier Life Peso',
    TR_EAZY_HEALTH_2000_PHP_NG_AGENCY: 'premiumTotal',
    TR_EAZY_HEALTH_2000_PHP_NG_ALT: 'premiumTotal',
    TR_EAZY_HEALTH_2000_PHP_NG_HSBC: 'premiumTotal',
    TR_EAZY_HEALTH_2000_PHP_NG_PNB: 'premiumTotal',
    TR_EAZY_HEALTH_2000_PHP_NG_WST_LTG: 'premiumTotal',
    TR_EAZY_HEALTH_500_PHP_NG_AGENCY: 'premiumTotal',
    TR_EAZY_HEALTH_500_PHP_NG_ALT: 'premiumTotal',
    TR_EAZY_HEALTH_500_PHP_NG_HSBC: 'premiumTotal',
    TR_EAZY_HEALTH_500_PHP_NG_PNB: 'premiumTotal',
    TR_EAZY_HEALTH_500_PHP_NG_WST_LTG: 'premiumTotal',
    TR_EAZY_PROTECT_PHP_NG_PNB: 'eAZy Protect',
    TR_HERO_10_PHP_NG_AGENCY: 'Hero 10 Version 2',
    TR_HERO_10_PHP_NG_PNB: 'Hero 10 Version 2',
    TR_HERO_15_PHP_NG_AGENCY: 'Hero 15 Version 2',
    TR_HERO_15_PHP_NG_PNB: 'Hero 15 Version 2',
    TR_INTENSIFY10_PHP_NG_PNB: '10-Pay Peso Intensify!',
    UL_SHIELD_PHP_NG_AGENCY: 'modalPremium',
    UL_SHIELD_USD_GAE_AGENCY: 'modalPremium',
    UL_SHIELD_USD_NG_AGENCY: 'modalPremium',
    UL_SHIELD_PHP_GAE_AGENCY: 'modalPremium',
    TR_AZ_PROTECT_YRT_PHP_NG_AGENCY: 'Allianz Protect Yearly Renewable Term (YRT)',
    TR_AZ_PROTECT_5YT_PHP_NG_AGENCY: 'Allianz Protect 5-Year Renewable Term (5YT)',
    TR_AZ_PROTECT_10YT_PHP_NG_AGENCY: 'Allianz Protect 10-Year Renewable Term (10YT)',
    IHP_WELL_PHP_AGENCY: 'Allianz Well!',
    IHP_WELL_PHP_PNB: 'Allianz Well!',
    IHP_WELL_PHP_WST_LTG: 'Allianz Well!',
    TR_AZ_FUNDAMENTAL_PHP_NG_BUSS: "totalPremium",
    TR_AZ_FUNDAMENTAL_PHP_NG_AGENCY: "totalPremium",
    UL_POWERLINK_ELITE_PHP_GAE_AGENCY: "inputPremium",
    UL_POWERLINK_ELITE_USD_GAE_AGENCY: "inputPremium",
    UL_POWERLINK_ELITE_PHP_GAE_PNB: "inputPremium",
    UL_POWERLINK_ELITE_USD_GAE_PNB: "inputPremium",
    TR_AZ_FUNDAMENTAL_PHP_NG_PNB: "totalPremium",
    UL_SECURE_PRO_USD_NG_AGENCY: "modalPremium",
    UL_SECURE_PRO_PHP_NG_AGENCY: "modalPremium",
    UL_WEALTH_BUILDER_3_PHP_GAE_HSBC: "modalPremium",
    UL_WEALTH_BUILDER_3_USD_GAE_HSBC: "modalPremium",
    UL_WEALTH_BUILDER_5_PHP_GAE_HSBC: "modalPremium",
    UL_WEALTH_BUILDER_5_USD_GAE_HSBC: "modalPremium",
    UL_WEALTH_BUILDER_10_PHP_GAE_HSBC: "modalPremium",
    UL_WEALTH_BUILDER_10_USD_GAE_HSBC: "modalPremium"
}
