export const SignaturePageList = {
	NA: 'NEEDS ANALYSIS',
	NAW: 'NEEDS ANALYSIS WAIVER',
	IRPQ: 'INVESTOR RISK PROFILE QUESTIONNAIRE',
	SI: 'SALES ILLUSTRATION',
	APPFORM: 'APPLICATION FORM',
	RNF: 'REPLACEMENT NOTIFICATION FORM',
	AFMORI: 'AUTHORIZATION TO FURNISH MEDICAL OR OTHER RELATED INFORMATION',
	CIC: 'CERTIFICATE OF INTERIM',
	REF: 'REFERROR AND REFERRING BRANCH DETAILS',
	REP: 'DECLARATION ON THE PROPOSED REPLACEMENT OF EXISTING POLICY(IES)',
	SIGN: 'SIGNATURE'
}