export const LOGTYPE = {
    btnClick: 'BUTTON CLICKED',
    cardSel: 'CARD SELECTED',
    error: 'ERROR',
    fullSync: 'FULL SYNC',
    pageSel: 'PAGE SELECTED',
    unsyncData: 'UNSYNCED DATA',
    sync: 'SYNC',
    syncReq: 'SYNC REQUEST',
    syncRes: 'SYNC RESPONSE',
    dbRetrieve: 'Database Attached Data Retrieve : ',
    START: 'START : ',
    END: 'END : ',
    paymentData: 'EPAYMENT DATA',
    getPaymentReq: 'GET PAYMENT REQUEST',
    getPaymentRes: 'GET PAYMENT RESPONSE',
    getPaymentError: 'GET PAYMENT ERROR',
    postPaymentReq: 'POST PAYMENT REQUEST',
    postPaymentRes: 'POST PAYMENT RESPONSE',
    postPaymentError: 'POST PAYMENT ERROR',
    startDeltaSync: 'DELTA SYNC START: ',
    endDeltaSync: 'DELTA SYNC END: ',
    errorDeltaSync: 'DELTA SYNC ERROR: '
}