export {
    PageTitleSpecs,
    PageDetailsSpecs,
    NetWorthSpecs,
    AnnualIncomeSpecs,
    ImportantObjSpecs,
    ImportantObjOthersSpecs,
    PleaseSelectSpecs,
    CurrentlyHaveSpecs,
    UsedTohaveSpecs,
    LifeInsuranceSpecs,
    LifeInsuranceRadioSpecs,
    CorporateBondsSpecs,
    CorporateBondsRadioSpecs,
    TimeDepositeSpecs,
    TimeDepositeRadioSpecs,
    DerivativesSpecs,
    DerivativesRadioSpecs,
    MutualFundSpecs,
    MutualFundRadioSpecs,
    RealEstateSpecs,
    RealEstateRadioSpecs,
    StocksSpecs,
    StocksRadioSpecs,
    OwnBusinessSpecs,
    OwnBusinessRadioSpecs,
    GovtSecuritiesSpecs,
    GovtSecuritiesRadioSpecs,
    NextButtonColumnSpecs
} from '@utils/constants/form/column-specs/irpq/general-info-column-specs'

export {
    PageDetailsSpecsPQ,
    Q1QuestionSpecs,
    Q2QuestionSpecs,
    Q3QuestionSpecs,
    Q4QuestionSpecs,
    Q5QuestionSpecs,
    Q6QuestionSpecs,
    Q7QuestionSpecs,
    Q8QuestionSpecs,
    Q1ChoicesSpecs,
    Q2ChoicesSpecs,
    Q3ChoicesSpecs,
    Q4ChoicesSpecs,
    Q5ChoicesSpecs,
    Q6ChoicesSpecs,
    Q7ChoicesSpecs,
    Q8ChoicesSpecs,
    PrevSlideButtonSpecs,
    NextSlideFirstButtonSpecs,
    NextSlideButtonSpecs,
    SubmitSlideButtonSpecs
} from '@utils/constants/form/column-specs/irpq/irpq-profile-column-spec'