import { FormBuilder, FormGroup, Validators } from '@angular/forms'
import { ForeignTravelCountriesFGControl, DetoxDoctorsFGControls, AlcoholDoctorsFGControlsConfig, VesselOpFGControls } from '@fg-controls/e-app';
import { REGEXP } from '@utils/constants/regexp/regexp';

export const NonMedPBRFormGroup: FormGroup = new FormBuilder().group({
  height: [null, [Validators.pattern(REGEXP.NUMERIC)]],
  heightCM: [null, [Validators.required, Validators.max(999), Validators.pattern(REGEXP.NUMBER)]],
  heightFT: [null, [Validators.pattern(REGEXP.WHOLE_NUMBER)]],
  heightIN: [null, [Validators.pattern(REGEXP.NUMBER)]],
  weightLBS: [],
  weightKG: [null, [Validators.required, Validators.maxLength(3), Validators.pattern(REGEXP.NUMERIC)]],
  cardiovascularDisFamilyCount: [null,  Validators.required], 
  cerebrovascularDisFamilyCount: [null, Validators.required], 
  diabetesFamilyCount: [null, Validators.required], 
  alzheimersFamilyCount: [null, Validators.required], 
  kidneyDisFamilyCount: [null, Validators.required], 
  cancerFamilyCount: [null, Validators.required], 
  cancerTypeCount: [null, Validators.required], 
  haveConsulted: [null, Validators.required],
  medConsultation: [],
  medConsultationNormal: [null, Validators.required],
  medConditions: [null, Validators.required],
  refferredForConsultation: [],
  haveDisease: [null, Validators.required],
  haveSymptomps: [],
  signsAndSymptomps: [],
  smokingNoOfYrs: [],
  smokingNoOfStick: [],
  smokingNoOfStickUnit: [],
  didSmoked: [],
  hadFormingDrugs: [],
  didDrink: [],
  alcoholType: [],
  drinkUnitValue: [],
  drinkUnit: [],
  drinkFreqUnit: [],
  drinkFreqValue: [],
  hadOpiates: [],
  hadOpiatesFrom: [],
  hadOpiatesTo: [],
  hadBarbiturates: [],
  hadBarbituratesFrom: [],
  hadBarbituratesTo: [],
  hadSedatives: [],
  hadSedativesFrom: [],
  hadSedativesTo: [],
  hadAphetamines: [],
  hadAphetaminesFrom: [],
  hadAphetaminesTo: [],
  hadCocaine: [],
  hadCocaineFrom: [],
  hadCocaineTo: [],
  hadHallucinogens: [],
  hadHallucinogensFrom: [],
  hadHallucinogensTo: [],
  hadCannabis: [],
  hadCannabisFrom: [],
  hadCannabisTo: [],
  hadSolvents: [],
  hadSolventsFrom: [],
  hadSolventsTo: [],
  hadOthers: [],
  hadOthersFrom: [],
  hadOthersTo: [],
  didSeekSupportRehab: [],
  didNotSmokeDrinkDrug: [],
  pregnantWeeks: [],
  isPregnant: [],
  cancerConditionDiagnosis: [],
  familyConditions: new FormBuilder().array([]),


  // -----------------
  hasHighBlood: [{ value: false, disabled: true }],
  hasLungDisease: [{ value: false, disabled: true }],
  hasMentalDysfunction: [{ value: false, disabled: true }],
  hasNeurologicalDysfunction: [{ value: false, disabled: true }],
  hasBloodDisease: [{ value: false, disabled: true }],
  hasPhysicalDeformity: [{ value: false, disabled: true }],

  hasDiabetes: [{ value: false, disabled: true }],
  hasSkinMuscleDisorder: [{ value: false, disabled: true }],
  hasStomachProblems: [{ value: false, disabled: true }],
  hasCongenitalDisorder: [{ value: false, disabled: true }],
  hasKidneyDisorder: [{ value: false, disabled: true }],
  hasCancer: [{ value: false, disabled: true }],
  hasAbnormalGrowth: [{ value: false, disabled: true }],
  hasOtherDefect: [{ value: false, disabled: true }],
  hasLipids: [{ value: false, disabled: true }],

  didConsult: [],  
  alcoholDoctors: new FormBuilder().array([]),
  detoxDoctors: new FormBuilder().array([]),
  // Declaration of Occupation
  changeOccupation: [null, Validators.required],
  occupation: [null, Validators.required],
  occupationClass: [null, Validators.required],
  branchArmy: ['', [Validators.required]],
  militaryRank: ['', [Validators.required]],
  airlineJobType: [null, [Validators.required]], 
  airCraftType: [null, [Validators.required]], 
  flyingHours: [null, [Validators.required]], 
  vesselOwner: ['', [Validators.required]],
  vesselType: ['', [Validators.required]],
  vesselCountry: ['', [Validators.required]],
  isPoliticallySensitive: ['', [Validators.required]],
  vesselOperationInfoNMED: new FormBuilder().array([]),
  changeCountryResidence: [null, Validators.required],
  countryResidence: ['', [Validators.required]],
  travelPurpose: [],
  purposeOccupation: [],
  purposeBusinessTrip: [],
  purposeImmigration: [],
  purposeBusinessTravel: [],
  purposeEducation: [],
  foreignOccupation: [null, [Validators.required]],
  planToTravelOrResideAbroad: [null, Validators.required],
  foreignTravelCountry: new FormBuilder().array([]),
  didBoxing: [],
  didMartialArts: [],
  didHanggliding: [],
  didMountaineering: [],
  didBiking: [],
  didIceHockey: [],
  didJetski: [],
  didDiving: [],
  didAerodium: [],
  didBallSport: [],
  didWrestling: [],
  didBungeeJumping: [],
  didMotorRacing: [],
  didHorseRacing: [],
  didCanyoning: [],
  didMountainBiking: [],
  didParachuting: [],
  didSandboarding: [],
  didyachting: [],
  didRafting: [],
  didPowerboatRacing: [],
  didSeaKayaking: [],
  didOtherSports: [],
  didSurfing: [], 
  didTriathlon: [],
  boxingType: [null, [Validators.required]],
  willBeProBoxer: [null, [Validators.required]],
  divingType: [null, [Validators.required]],
  divingDepth: [null, [Validators.required]],
  divingMxDepth: [null, [Validators.required]],
  needsDivingDecompression: [null, [Validators.required]],
  nightDiving: [null, [Validators.required]],
  caveDiving: [null, [Validators.required]],
  iceDiving: [null, [Validators.required]],
  unaccompaniedDiving: [null, [Validators.required]],
  divingParticipation: [],
  parasailingType: [null, [Validators.required]],
  parasailingPastYr: [null, [Validators.required]],
  parasailingUpcomingYr: [null, [Validators.required]],
  parasailingflyingCompetition: [null, [Validators.required]],
  motorRacingType: [null, [Validators.required]],
  motorRacingDragRacing: [null, [Validators.required]],
  motorRacingGrassTrack: [null, [Validators.required]],
  motorRacingHillClimbs: [null, [Validators.required]],
  motorRacingIceRacing: [null, [Validators.required]],
  motorRacingMotorCross: [null, [Validators.required]],
  motorRacingSandRacing: [null, [Validators.required]],
  motorRacingSpeedways: [null, [Validators.required]],
  motorRacingTrials: [null, [Validators.required]],
  motorRacingIceRacingPro: [null, [Validators.required]],
  motorRacingMotorCrossPro: [null, [Validators.required]],
  motorRacingSpeedwayPro: [null, [Validators.required]],
  motorRacingParticipation: [null, [Validators.required]],
  joinedMountainHiking: [],
  joinedRockClimbing: [],
  joinedBouldering: [],
  joinedFreeSoloClimbing: [],
  parachuteType: [null, [Validators.required]],
  parachuteNo: [null, [Validators.required]],
  joinedOffShoreRacing: [],
  joinedCatamarans: [],
  joinedDrugBoat: [],
  joinedHydroplane: [],
  joinedCircuitRacingMono: [],
  yachtingEngagementReason: [null, [Validators.required]],
  yachtType: [null, [Validators.required]],
  yachtingCrewNo: [null, [Validators.required]  ],
  martialArtsType: [null, [Validators.required]],
  martialArtsFreq: [null, [Validators.required]],
  martialArtsWeapon: [null, [Validators.required]],
  raftingType: [null, [Validators.required]],
  raftingFreq: [null, [Validators.required]],
  noneOfActivities: [],
  otherSportEngagementReason: [],
  otherSportFreq: [],
  illnessWhen: [],
  illnessHow: [],
  illnessInjuryBone: [],
  illnessInjuryLimb: [],
  illnessInjurySpinal: [],
  illnessInjuryHead: [],
  illnessInjuryWound: [],
  illnessInjuryOrgan: [],
  illnessTreatment: [],
  illnessHaveRecovered: [],
  illnessIsContemplated: []
});

export const ForeignTravelCountriesPBRFormGroup = new FormBuilder().group(ForeignTravelCountriesFGControl);
export const AlcoholDoctorsFormGroup: FormGroup = new FormBuilder().group(AlcoholDoctorsFGControlsConfig);
export const DetoxDoctorsFormGroup: FormGroup = new FormBuilder().group(DetoxDoctorsFGControls);
export const VesselOpFormGroup: FormGroup = new FormBuilder().group(VesselOpFGControls);
