
export const FUND_KEY = {
    DAMIPDPF: 'DAMIPDPF',
    DFIF: 'DFIF',
    DFABF: 'DFABF',
    DFADPBF: 'DFADPBF',
    DGEF: 'DGEF',
    DGEPF: 'DGEPF',
    DGLIDPF: 'DGLIDPF',
    DGODPBF: 'DGODPBF',
    DGRADPF: 'DGRADPF',
    DIGDPF: 'DIGDPF',
    DIGF: 'DIGF',
    PBDPF: 'PBDPF',
    PBF: 'PBF',
    PDEF: 'PDEF',
    PEF: 'PEF',
    PFIF: 'PFIF',
    PMMF: 'PMMF',
    PMSEF: 'PMSEF',
    PODEF: 'PODEF',
    PHAMIPDPF: 'PHAMIPDPF',
    PHGRADPF: 'PHGRADPF',
    PHIAGDPF: 'PHIAGDPF',
    PHGSEF: 'PHGSEF',
    PHSGEDPF: 'PHSGEDPF',
    PHDIDPF: 'PHDIDPF',
    DSGEDPF: 'DSGEDPF',
    PSPDPF: 'PSPDPF',
    DSPDPF: 'DSPDPF',
    PEPGF: 'PEPGF',
    DEPGF: 'DEPGF',
}

export const FUNDS = {
    [FUND_KEY.DAMIPDPF]: 'Dollar Asian Multi-Income Plus Dividend Paying Fund',
    [FUND_KEY.DFIF]: 'Dollar Fixed Income Fund',
    [FUND_KEY.DFABF]: 'Dollar Flexi Asia Bond Fund',
    [FUND_KEY.DFADPBF]: 'Dollar Flexi Asia Dividend Paying Bond Fund',
    [FUND_KEY.DGEF]: 'Dollar Global Equity Fund',
    [FUND_KEY.DGEPF]: 'Dollar Global Equity Plus Fund',
    [FUND_KEY.DGLIDPF]: 'Dollar Global Income Dividend-Paying Fund',
    [FUND_KEY.DGODPBF]: 'Dollar Global Opportunistic Dividend Paying Bond Fund',
    [FUND_KEY.DIGDPF]: 'Dollar Income and Growth Dividend Paying Fund',
    [FUND_KEY.DGRADPF]: 'Dollar Global Real Assets Dividend Paying Fund',
    [FUND_KEY.DIGF]: 'Dollar Income and Growth Fund',
    [FUND_KEY.DSGEDPF]: 'Dollar Systematic Global Equity Dividend Paying Fund',
    [FUND_KEY.DSPDPF]: 'Dollar Stability Plus Dividend Paying Fund',

    [FUND_KEY.PBDPF]: 'Peso Balanced Dividend-Paying Fund',
    [FUND_KEY.PBF]: 'Peso Balanced Fund',
    [FUND_KEY.PDEF]: 'Peso Dynasty Equity Fund',
    [FUND_KEY.PEF]: 'Peso Equity Fund',
    [FUND_KEY.PFIF]: 'Peso Fixed Income Fund',
    [FUND_KEY.PMMF]: 'Peso Money Market Fund',
    [FUND_KEY.PMSEF]: 'Peso Multi-Sector Equity Fund',
    [FUND_KEY.PODEF]: 'Peso Optimized Dividend Equity Fund',
    [FUND_KEY.PHAMIPDPF]: 'Peso-Hedged Asian Multi-Income Plus Dividend Paying Fund',
    [FUND_KEY.PHGRADPF]: 'Peso-Hedged Global Real Assets Dividend Paying Fund',
    [FUND_KEY.PHIAGDPF]: 'Peso-Hedged Income and Growth Dividend Paying Fund',
    [FUND_KEY.PHGSEF]: 'Peso-Hedged Global Sustainability Equity Fund',
    [FUND_KEY.PHDIDPF]: 'Peso-Hedged Diversified Income Dividend Paying Fund',
    [FUND_KEY.PHSGEDPF]: 'Peso-Hedged Systematic Global Equity Dividend Paying Fund',
    [FUND_KEY.PSPDPF]: 'Peso Stability Plus Dividend Paying Fund',
    [FUND_KEY.PEPGF]: 'Peso Equity Power Growth Fund',
    [FUND_KEY.DEPGF]: 'Dollar Equity Power Growth Fund',
}


export const DIVIDEND_PAYING_FUNDS = [
    FUND_KEY.DAMIPDPF,
    FUND_KEY.DFADPBF,
    FUND_KEY.DGLIDPF,
    FUND_KEY.DGRADPF,
    FUND_KEY.DGODPBF,
    FUND_KEY.DIGDPF,
    FUND_KEY.PBDPF,
    FUND_KEY.PHGRADPF,
    FUND_KEY.PHIAGDPF,
    FUND_KEY.PHAMIPDPF,
    FUND_KEY.PODEF,
    FUND_KEY.PHSGEDPF,
    FUND_KEY.PHDIDPF,
    FUND_KEY.DSGEDPF,
    FUND_KEY.PSPDPF,
    FUND_KEY.DSPDPF
]