export const PLANS = {
    UL_AZ_GENESIS_PHP_NG_HSBC: 'ALLIANZ GENESIS',
    UL_AZ_GENESIS_USD_NG_HSBC: 'ALLIANZ GENESIS',
    UL_AZ_PROSPERITY_PHP_GAE_HSBC: 'Allianz Prosperity Peso',
    UL_AZ_PROSPERITY_USD_GAE_HSBC: 'Allianz Prosperity Dollar',
    TR_ACHIEVERS_PHP_NG_PNB: 'Achievers Version 2',
    TR_BIDA_10_PHP_NG_AGENCY: 'Bida! 10 Version 2',
    TR_BIDA_10_PHP_NG_PNB: 'Bida! 10 Version 2',
    TR_BIDA_15_PHP_NG_AGENCY: 'Bida! 15 Version 2',
    TR_BIDA_15_PHP_NG_PNB: 'Bida! 15 Version 2',
    TR_EAZY_HEALTH_1000_PHP_NG_AGENCY: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_ALT: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_HSBC: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_PNB: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_WST_LTG: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1500_PHP_NG_AGENCY: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_ALT: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_HSBC: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_PNB: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_WST_LTG: 'Allianz eAZy Health Gold',
    TR_TERM10_PHP_NG_PNB: 'Renewable & Convertible Term 10-year',
    TR_TERM15_PHP_NG_PNB: 'Renewable & Convertible Term 15-year',
    TR_TERM1_PHP_NG_PNB: 'Renewable & Convertible Term 1-year',
    TR_TERM5_PHP_NG_PNB: 'Renewable & Convertible Term 5-year',
    UL_AZPIRE_GROWTH_PHP_GAE_AGENCY: 'AZpire Growth Pro - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_HSBC: 'AZpire Growth Plus - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_PNB: 'AZpire Growth Prime - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_WST_LTG: 'AZpire Growth Prime - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_NG_AGENCY: 'AZpire Growth Pro - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_HSBC: 'AZpire Growth Plus - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_PNB: 'AZpire Growth Prime - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_WST_LTG: 'AZpire Growth Prime - Peso',
    UL_AZPIRE_GROWTH_USD_GAE_AGENCY: 'AZpire Growth Pro - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_HSBC: 'AZpire Growth Plus - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_PNB: 'AZpire Growth Prime - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_WST_LTG: 'AZpire Growth Prime - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_NG_AGENCY: 'AZpire Growth Pro - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_HSBC: 'AZpire Growth Plus - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_PNB: 'AZpire Growth Prime - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_WST_LTG: 'AZpire Growth Prime - Dollar',
    UL_AZPIRE_PEAK_PHP_GAE_AGENCY: 'AZpire Peak Pro - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_GAE_HSBC: 'AZpire Peak Plus - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_GAE_PNB: 'AZpire Peak Prime - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_NG_AGENCY: 'AZpire Peak Pro - Peso',
    UL_AZPIRE_PEAK_PHP_NG_HSBC: 'AZpire Peak Plus - Peso',
    UL_AZPIRE_PEAK_PHP_NG_PNB: 'AZpire Peak Prime - Peso',
    UL_DIVERSIFY_USD_NG_AGENCY: 'DIVERSIFY DOLLAR VER. 2',
    UL_DIVERSIFY_USD_NG_PNB: 'DIVERSIFY DOLLAR VER. 2',
    UL_HEALTH_10_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_10_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_10_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_10_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_20_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_20_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_20_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_20_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_MAXIMAL_PHP_NG_AGENCY: 'MAXIMAL POWER PESO',
    UL_MAXIMAL_PHP_NG_PNB: 'MAXIMAL POWER PESO',
    UL_MAXIMAL_USD_NG_AGENCY: 'MAXIMAL POWER DOLLAR',
    UL_MAXIMAL_USD_NG_PNB: 'MAXIMAL POWER DOLLAR',
    UL_OPTIMAL_PHP_NG_AGENCY: 'OPTIMAL POWER PESO',
    UL_OPTIMAL_PHP_NG_PNB: 'OPTIMAL POWER PESO',
    UL_OPTIMAL_USD_NG_AGENCY: 'OPTIMAL POWER DOLLAR',
    UL_OPTIMAL_USD_NG_PNB: 'OPTIMAL POWER DOLLAR',
    UL_OPTIMAX_PHP_GAE_PNB: 'OPTIMAX GOLD',
    UL_OPTIMAX_USD_GAE_PNB: 'OPTIMAX GREEN',
    UL_OPTIMAX_PHP_GAE_AGENCY: 'OPTIMAX GOLD',
    UL_OPTIMAX_USD_GAE_AGENCY: 'OPTIMAX GREEN',
    UL_OPTIMUM_PHP_GAE_AGENCY: 'OPTIMUM GOLD',
    UL_OPTIMUM_PHP_GAE_PNB: 'OPTIMUM GOLD',
    UL_OPTIMUM_USD_GAE_AGENCY: 'OPTIMUM GREEN',
    UL_OPTIMUM_USD_GAE_PNB: 'OPTIMUM GREEN',
    UL_AZPIRE_PEAK_USD_GAE_AGENCY: 'AZpire Peak Pro - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_GAE_HSBC: 'AZpire Peak Plus - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_GAE_PNB: 'AZpire Peak Prime - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_NG_AGENCY: 'AZpire Peak Pro - Dollar',
    UL_AZPIRE_PEAK_USD_NG_HSBC: 'AZpire Peak Plus - Dollar',
    UL_AZPIRE_PEAK_USD_NG_PNB: 'AZpire Peak Prime - Dollar',
    UL_AZPIRE_WIZ_PHP_GAE_AGENCY: 'AZpire Wiz Pro - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_GAE_HSBC: 'AZpire Wiz Plus - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_GAE_PNB: 'AZpire Wiz Prime - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_NG_AGENCY: 'AZpire Wiz Pro - Peso',
    UL_AZPIRE_WIZ_PHP_NG_HSBC: 'AZpire Wiz Plus - Peso',
    UL_AZPIRE_WIZ_PHP_NG_PNB: 'AZpire Wiz Prime - Peso',
    UL_AZPIRE_WIZ_USD_GAE_AGENCY: 'AZpire Wiz Pro - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_GAE_HSBC: 'AZpire Wiz Plus - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_GAE_PNB: 'AZpire Wiz Prime - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_NG_AGENCY: 'AZpire Wiz Pro - Dollar',
    UL_AZPIRE_WIZ_USD_NG_HSBC: 'AZpire Wiz Plus - Dollar',
    UL_AZPIRE_WIZ_USD_NG_PNB: 'AZpire Wiz Prime - Dollar',
    UL_DIVERSIFY_PHP_GAE_AGENCY: 'DIVERSIFY PESO VER. 2 WITH GAE',
    UL_DIVERSIFY_PHP_GAE_PNB: 'DIVERSIFY PESO VER. 2 WITH GAE',
    UL_DIVERSIFY_PHP_NG_AGENCY: 'DIVERSIFY PESO VER. 2',
    UL_DIVERSIFY_PHP_NG_PNB: 'DIVERSIFY PESO VER. 2',
    UL_DIVERSIFY_USD_GAE_AGENCY: 'DIVERSIFY DOLLAR VER. 2 WITH GAE',
    UL_DIVERSIFY_USD_GAE_PNB: 'DIVERSIFY DOLLAR VER. 2 WITH GAE',
    TR_INTENSIFY4_PHP_GAE_PNB: '4-Pay Peso Intensify! with GAE',
    TR_INTENSIFY4_PHP_NG_PNB: '4-Pay Peso Intensify!',
    TR_INTENSIFY6_PHP_GAE_PNB: '6-Pay Peso Intensify! with GAE',
    TR_INTENSIFY6_PHP_NG_PNB: '6-Pay Peso Intensify!',
    TR_INTENSIFY8_PHP_NG_PNB: '8-Pay Peso Intensify!',
    TR_PREMIER_LIFE10_PHP_NG_PNB: '10-Pay Premier Life Peso',
    TR_PREMIER_LIFE_PHP_NG_PNB: 'Premier Life Peso',
    TR_EAZY_HEALTH_2000_PHP_NG_AGENCY: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_ALT: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_HSBC: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_PNB: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_WST_LTG: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_500_PHP_NG_AGENCY: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_ALT: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_HSBC: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_PNB: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_WST_LTG: 'Allianz eAZy Health Blue',
    TR_EAZY_PROTECT_PHP_NG_PNB: 'eAZy Protect',
    TR_HERO_10_PHP_NG_AGENCY: 'Hero 10 Version 2',
    TR_HERO_10_PHP_NG_PNB: 'Hero 10 Version 2',
    TR_HERO_15_PHP_NG_AGENCY: 'Hero 15 Version 2',
    TR_HERO_15_PHP_NG_PNB: 'Hero 15 Version 2',
    TR_INTENSIFY10_PHP_NG_PNB: '10-Pay Peso Intensify!',
    UL_SHIELD_PHP_NG_AGENCY: 'ALLIANZ SHIELD PESO',
    UL_SHIELD_USD_GAE_AGENCY: 'ALLIANZ SHIELD DOLLAR WITH GAE',
    UL_SHIELD_USD_NG_AGENCY: 'ALLIANZ SHIELD DOLLAR',
    UL_SHIELD_PHP_GAE_AGENCY: 'ALLIANZ SHIELD PESO WITH GAE',
    TR_AZ_PROTECT_YRT_PHP_NG_AGENCY: 'Allianz Protect Yearly Renewable Term (YRT)',
    TR_AZ_PROTECT_5YT_PHP_NG_AGENCY: 'Allianz Protect 5-Year Renewable Term (5YT)',
    TR_AZ_PROTECT_10YT_PHP_NG_AGENCY: 'Allianz Protect 10-Year Renewable Term (10YT)',
    IHP_WELL_PHP_AGENCY: 'Allianz Well!',
    IHP_WELL_PHP_PNB: 'Allianz Well!',
    IHP_WELL_PHP_WST_LTG: 'Allianz Well!',
    TR_AZ_FUNDAMENTAL_PHP_NG_BUSS: "Allianz Fundamental Cover",
    TR_AZ_FUNDAMENTAL_PHP_NG_AGENCY: "Allianz Fundamental Cover",
    UL_POWERLINK_ELITE_PHP_GAE_AGENCY: "Allianz Powerlink Elite",
    UL_POWERLINK_ELITE_USD_GAE_AGENCY: "Allianz Powerlink Elite",
    UL_POWERLINK_ELITE_PHP_GAE_PNB: "Allianz Powerlink Elite",
    UL_POWERLINK_ELITE_USD_GAE_PNB: "Allianz Powerlink Elite",
    TR_AZ_FUNDAMENTAL_PHP_NG_PNB: "Allianz Fundamental Cover",
    UL_SECURE_PRO_PHP_NG_AGENCY: "ALLIANZ SECURE PRO",
    UL_SECURE_PRO_USD_NG_AGENCY: "ALLIANZ SECURE PRO",
    UL_WEALTH_BUILDER_3_PHP_GAE_HSBC: "Allianz Wealth Builder 3",
    UL_WEALTH_BUILDER_3_USD_GAE_HSBC: "Allianz Wealth Builder 3",
    UL_WEALTH_BUILDER_5_PHP_GAE_HSBC: "Allianz Wealth Builder 5",
    UL_WEALTH_BUILDER_5_USD_GAE_HSBC: "Allianz Wealth Builder 5",
    UL_WEALTH_BUILDER_10_PHP_GAE_HSBC: "Allianz Wealth Builder 10",
    UL_WEALTH_BUILDER_10_USD_GAE_HSBC: "Allianz Wealth Builder 10",
}

export const PLAN_TITLE = {
    UL_AZ_GENESIS_PHP_NG_HSBC: 'ALLIANZ GENESIS',
    UL_AZ_GENESIS_USD_NG_HSBC: 'ALLIANZ GENESIS',
    UL_AZ_PROSPERITY_PHP_GAE_HSBC: 'Allianz Prosperity Peso',
    UL_AZ_PROSPERITY_USD_GAE_HSBC: 'Allianz Prosperity Dollar',
    TR_ACHIEVERS_PHP_NG_PNB: 'Achievers Version 2',
    TR_BIDA_10_PHP_NG_AGENCY: 'Bida! 10 Version 2',
    TR_BIDA_10_PHP_NG_PNB: 'Bida! 10 Version 2',
    TR_BIDA_15_PHP_NG_AGENCY: 'Bida! 15 Version 2',
    TR_BIDA_15_PHP_NG_PNB: 'Bida! 15 Version 2',
    TR_EAZY_HEALTH_1000_PHP_NG_AGENCY: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_ALT: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_HSBC: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_PNB: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1000_PHP_NG_WST_LTG: 'Allianz eAZy Health Silver',
    TR_EAZY_HEALTH_1500_PHP_NG_AGENCY: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_ALT: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_HSBC: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_PNB: 'Allianz eAZy Health Gold',
    TR_EAZY_HEALTH_1500_PHP_NG_WST_LTG: 'Allianz eAZy Health Gold',
    TR_TERM10_PHP_NG_PNB: 'Renewable & Convertible Term 10-year',
    TR_TERM15_PHP_NG_PNB: 'Renewable & Convertible Term 15-year',
    TR_TERM1_PHP_NG_PNB: 'Renewable & Convertible Term 1-year',
    TR_TERM5_PHP_NG_PNB: 'Renewable & Convertible Term 5-year',
    UL_AZPIRE_GROWTH_PHP_GAE_AGENCY: 'AZpire Growth Pro - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_HSBC: 'AZpire Growth Plus - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_PNB: 'AZpire Growth Prime - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_GAE_WST_LTG: 'AZpire Growth Prime - Peso with GAE',
    UL_AZPIRE_GROWTH_PHP_NG_AGENCY: 'AZpire Growth Pro - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_HSBC: 'AZpire Growth Plus - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_PNB: 'AZpire Growth Prime - Peso',
    UL_AZPIRE_GROWTH_PHP_NG_WST_LTG: 'AZpire Growth Prime - Peso',
    UL_AZPIRE_GROWTH_USD_GAE_AGENCY: 'AZpire Growth Pro - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_HSBC: 'AZpire Growth Plus - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_PNB: 'AZpire Growth Prime - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_GAE_WST_LTG: 'AZpire Growth Prime - Dollar with GAE',
    UL_AZPIRE_GROWTH_USD_NG_AGENCY: 'AZpire Growth Pro - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_HSBC: 'AZpire Growth Plus - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_PNB: 'AZpire Growth Prime - Dollar',
    UL_AZPIRE_GROWTH_USD_NG_WST_LTG: 'AZpire Growth Prime - Dollar',
    UL_AZPIRE_PEAK_PHP_GAE_AGENCY: 'AZpire Peak Pro - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_GAE_HSBC: 'AZpire Peak Plus - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_GAE_PNB: 'AZpire Peak Prime - Peso with GAE',
    UL_AZPIRE_PEAK_PHP_NG_AGENCY: 'AZpire Peak Pro - Peso',
    UL_AZPIRE_PEAK_PHP_NG_HSBC: 'AZpire Peak Plus - Peso',
    UL_AZPIRE_PEAK_PHP_NG_PNB: 'AZpire Peak Prime - Peso',
    UL_DIVERSIFY_USD_NG_AGENCY: 'DIVERSIFY DOLLAR VER. 2',
    UL_DIVERSIFY_USD_NG_PNB: 'DIVERSIFY DOLLAR VER. 2',
    UL_HEALTH_10_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_10_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_10_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_10_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_20_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_20_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_20_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_20_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_PHP_NG_AGENCY: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_PHP_NG_PNB: 'HEALTH DYNAMICS PESO',
    UL_HEALTH_USD_NG_AGENCY: 'HEALTH DYNAMICS DOLLAR',
    UL_HEALTH_USD_NG_PNB: 'HEALTH DYNAMICS DOLLAR',
    UL_MAXIMAL_PHP_NG_AGENCY: 'MAXIMAL POWER PESO',
    UL_MAXIMAL_PHP_NG_PNB: 'MAXIMAL POWER PESO',
    UL_MAXIMAL_USD_NG_AGENCY: 'MAXIMAL POWER DOLLAR',
    UL_MAXIMAL_USD_NG_PNB: 'MAXIMAL POWER DOLLAR',
    UL_OPTIMAL_PHP_NG_AGENCY: 'OPTIMAL POWER PESO',
    UL_OPTIMAL_PHP_NG_PNB: 'OPTIMAL POWER PESO',
    UL_OPTIMAL_USD_NG_AGENCY: 'OPTIMAL POWER DOLLAR',
    UL_OPTIMAL_USD_NG_PNB: 'OPTIMAL POWER DOLLAR',
    UL_OPTIMAX_PHP_GAE_PNB: 'OPTIMAX GOLD',
    UL_OPTIMAX_USD_GAE_PNB: 'OPTIMAX GREEN',
    UL_OPTIMAX_PHP_GAE_AGENCY: 'OPTIMAX GOLD',
    UL_OPTIMAX_USD_GAE_AGENCY: 'OPTIMAX GREEN',
    UL_OPTIMUM_PHP_GAE_AGENCY: 'OPTIMUM GOLD',
    UL_OPTIMUM_PHP_GAE_PNB: 'OPTIMUM GOLD',
    UL_OPTIMUM_USD_GAE_AGENCY: 'OPTIMUM GREEN',
    UL_OPTIMUM_USD_GAE_PNB: 'OPTIMUM GREEN',
    UL_AZPIRE_PEAK_USD_GAE_AGENCY: 'AZpire Peak Pro - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_GAE_HSBC: 'AZpire Peak Plus - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_GAE_PNB: 'AZpire Peak Prime - Dollar with GAE',
    UL_AZPIRE_PEAK_USD_NG_AGENCY: 'AZpire Peak Pro - Dollar',
    UL_AZPIRE_PEAK_USD_NG_HSBC: 'AZpire Peak Plus - Dollar',
    UL_AZPIRE_PEAK_USD_NG_PNB: 'AZpire Peak Prime - Dollar',
    UL_AZPIRE_WIZ_PHP_GAE_AGENCY: 'AZpire Wiz Pro - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_GAE_HSBC: 'AZpire Wiz Plus - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_GAE_PNB: 'AZpire Wiz Prime - Peso with GAE',
    UL_AZPIRE_WIZ_PHP_NG_AGENCY: 'AZpire Wiz Pro - Peso',
    UL_AZPIRE_WIZ_PHP_NG_HSBC: 'AZpire Wiz Plus - Peso',
    UL_AZPIRE_WIZ_PHP_NG_PNB: 'AZpire Wiz Prime - Peso',
    UL_AZPIRE_WIZ_USD_GAE_AGENCY: 'AZpire Wiz Pro - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_GAE_HSBC: 'AZpire Wiz Plus - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_GAE_PNB: 'AZpire Wiz Prime - Dollar with GAE',
    UL_AZPIRE_WIZ_USD_NG_AGENCY: 'AZpire Wiz Pro - Dollar',
    UL_AZPIRE_WIZ_USD_NG_HSBC: 'AZpire Wiz Plus - Dollar',
    UL_AZPIRE_WIZ_USD_NG_PNB: 'AZpire Wiz Prime - Dollar',
    UL_DIVERSIFY_PHP_GAE_AGENCY: 'DIVERSIFY PESO VER. 2 WITH GAE',
    UL_DIVERSIFY_PHP_GAE_PNB: 'DIVERSIFY PESO VER. 2 WITH GAE',
    UL_DIVERSIFY_PHP_NG_AGENCY: 'DIVERSIFY PESO VER. 2',
    UL_DIVERSIFY_PHP_NG_PNB: 'DIVERSIFY PESO VER. 2',
    UL_DIVERSIFY_USD_GAE_AGENCY: 'DIVERSIFY DOLLAR VER. 2 WITH GAE',
    UL_DIVERSIFY_USD_GAE_PNB: 'DIVERSIFY DOLLAR VER. 2 WITH GAE',
    TR_INTENSIFY4_PHP_GAE_PNB: '4-Pay Peso Intensify! with GAE',
    TR_INTENSIFY4_PHP_NG_PNB: '4-Pay Peso Intensify!',
    TR_INTENSIFY6_PHP_GAE_PNB: '6-Pay Peso Intensify! with GAE',
    TR_INTENSIFY6_PHP_NG_PNB: '6-Pay Peso Intensify!',
    TR_INTENSIFY8_PHP_NG_PNB: '8-Pay Peso Intensify!',
    TR_PREMIER_LIFE10_PHP_NG_PNB: '10-Pay Premier Life Peso',
    TR_PREMIER_LIFE_PHP_NG_PNB: 'Premier Life Peso',
    TR_EAZY_HEALTH_2000_PHP_NG_AGENCY: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_ALT: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_HSBC: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_PNB: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_2000_PHP_NG_WST_LTG: 'Allianz eAZy Health Platinum',
    TR_EAZY_HEALTH_500_PHP_NG_AGENCY: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_ALT: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_HSBC: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_PNB: 'Allianz eAZy Health Blue',
    TR_EAZY_HEALTH_500_PHP_NG_WST_LTG: 'Allianz eAZy Health Blue',
    TR_EAZY_PROTECT_PHP_NG_PNB: 'eAZy Protect',
    TR_HERO_10_PHP_NG_AGENCY: 'Hero 10 Version 2',
    TR_HERO_10_PHP_NG_PNB: 'Hero 10 Version 2',
    TR_HERO_15_PHP_NG_AGENCY: 'Hero 15 Version 2',
    TR_HERO_15_PHP_NG_PNB: 'Hero 15 Version 2',
    TR_INTENSIFY10_PHP_NG_PNB: '10-Pay Peso Intensify!',
    UL_SHIELD_PHP_NG_AGENCY: 'ALLIANZ SHIELD PESO',
    UL_SHIELD_USD_GAE_AGENCY: 'ALLIANZ SHIELD DOLLAR WITH GAE',
    UL_SHIELD_USD_NG_AGENCY: 'ALLIANZ SHIELD DOLLAR',
    UL_SHIELD_PHP_GAE_AGENCY: 'ALLIANZ SHIELD PESO WITH GAE',
    TR_AZ_PROTECT_YRT_PHP_NG_AGENCY: 'Allianz Protect Yearly Renewable Term (YRT)',
    TR_AZ_PROTECT_5YT_PHP_NG_AGENCY: 'Allianz Protect 5-Year Renewable Term (5YT)',
    TR_AZ_PROTECT_10YT_PHP_NG_AGENCY: 'Allianz Protect 10-Year Renewable Term (10YT)',
    IHP_WELL_PHP_AGENCY: 'Allianz Well!',
    IHP_WELL_PHP_PNB: 'Allianz Well!',
    IHP_WELL_PHP_WST_LTG: 'Allianz Well!',
    TR_AZ_FUNDAMENTAL_PHP_NG_BUSS: "Allianz Fundamental Cover",
    TR_AZ_FUNDAMENTAL_PHP_NG_AGENCY: "Allianz Fundamental Cover",
    UL_POWERLINK_ELITE_PHP_GAE_AGENCY: "Allianz Powerlink Elite Peso",
    UL_POWERLINK_ELITE_USD_GAE_AGENCY: "Allianz Powerlink Elite Dollar",
    UL_POWERLINK_ELITE_PHP_GAE_PNB: "Allianz Powerlink Elite Peso",
    UL_POWERLINK_ELITE_USD_GAE_PNB: "Allianz Powerlink Elite Dollar",
    TR_AZ_FUNDAMENTAL_PHP_NG_PNB: "Allianz Fundamental Cover",
    UL_SECURE_PRO_PHP_NG_AGENCY: "Allianz Secure Pro Peso",
    UL_SECURE_PRO_USD_NG_AGENCY: "Allianz Secure Pro Dollar",
    UL_WEALTH_BUILDER_3_PHP_GAE_HSBC: "Allianz Wealth Builder 3 Peso",
    UL_WEALTH_BUILDER_3_USD_GAE_HSBC: "Allianz Wealth Builder 3 Dollar",
    UL_WEALTH_BUILDER_5_PHP_GAE_HSBC: "Allianz Wealth Builder 5 Peso",
    UL_WEALTH_BUILDER_5_USD_GAE_HSBC: "Allianz Wealth Builder 5 Dollar",
    UL_WEALTH_BUILDER_10_PHP_GAE_HSBC: "Allianz Wealth Builder 10 Peso",
    UL_WEALTH_BUILDER_10_USD_GAE_HSBC: "Allianz Wealth Builder 10 Dollar",
}
