 export const RIDERS = {
    TR_ADB_PHP_0_PNB: 'Accidental Death Benefit Rider',
    TR_ADD_PHP_0_PNB: 'Accidental Death and Dismemberment Rider',
    TR_ADDD_0_PHP_PNB: 'Accidental Death, Disability and Dismemberment (ADDD) Benefit',
    TR_CI_0_PHP_PNB: 'Critical Illness (CI) Benefit',
    TR_DDR_PHP_0_PNB: 'Dread Disease Rider',
    TR_DDR5_PHP_0_PNB: 'Dread Disease Rider',
    TR_DDR10_PHP_0_PNB: 'Dread Disease Rider',
    TR_DDR15_PHP_0_PNB: 'Dread Disease Rider',
    TR_DHA_0_PHP_PNB: 'Daily Hospital Allowance (DHA) Benefit',
    TR_DTR10_PHP_0_PNB: '5-Pay 10-Yr Decreasing Term Rider',
    TR_DTR15_PHP_0_PNB: '5-Pay 15-Yr Decreasing Term Rider',
    TR_DTR20_PHP_0_PNB: '5-Pay 20-Yr Decreasing Term Rider',
    TR_FFR_PHP_0_PNB: 'Flexi Fund Rider',
    TR_PBR_PHP_0_PNB: `Payor's Benefit Rider`,
    TR_SAR_PHP_0_PNB: 'Special Accident Rider',
    TR_TPD_0_PHP_PNB: 'Total and Permanent Disability (TPD) Benefit',
    TR_TR1_PHP_0_PNB: '1-Year Term Rider',
    TR_TR10_PHP_0_PNB: '10-Year Term Rider',
    TR_TR15_PHP_0_PNB: '15-Year Term Rider',
    TR_TR20_PHP_0_PNB: '20-Year Term Rider',
    TR_TR5_PHP_0_PNB: '5-Year Term Rider',
    TR_WOP_PHP_0_PNB: 'Waiver of Premium Rider',
    UL_ADD_PHP_0_AGENCY: 'Accidental Death and Dismemberment',
    UL_ADD_USD_0_AGENCY: 'Accidental Death and Dismemberment',
    UL_ADD_PHP_0_HSBC_AZ: 'Accidental Death and Dismemberment',
    UL_ADD_PHP_0_PNB: 'Accidental Death and Dismemberment',
    UL_ADD_PHP_0_PNB_AZ: 'Accidental Death and Dismemberment',
    UL_ADD_PHP_0_WST_LTG_AZ: 'Accidental Death and Dismemberment',
    UL_ADD_USD_0_HSBC_AZ: 'Accidental Death and Dismemberment',
    UL_ADD_USD_0_PNB: 'Accidental Death and Dismemberment',
    UL_ADD_USD_0_PNB_AZ: 'Accidental Death and Dismemberment',
    UL_ADD_USD_0_WST_LTG_AZ: 'Accidental Death and Dismemberment',
    UL_CI100_PHP_0_HSBC_AZ: 'Critical Illness 100',
    UL_CI100_PHP_0_PNB: 'Critical Illness 100',
    UL_CI100_PHP_0_PNB_AZ: 'Critical Illness 100',
    UL_CI100_PHP_0_WST_LTG_AZ: 'Critical Illness 100',
    UL_CI100_USD_0_HSBC_AZ: 'Critical Illness 100',
    UL_CI100_USD_0_PNB: 'Critical Illness 100',
    UL_CI100_USD_0_PNB_AZ: 'Critical Illness 100',
    UL_CI100_USD_0_WST_LTG_AZ: 'Critical Illness 100',
    UL_CI100HD_PHP_0_PNB: 'Critical Illness 100',
    UL_CI100HD_USD_0_PNB: 'Critical Illness 100',
    UL_WPCI05_PHP_0_PNB: '5-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI05_PHP_0_PNB_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI05_USD_0_PNB: '5-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI05_USD_0_PNB_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_PHP_0_PNB: '10-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI10_PHP_0_PNB_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_USD_0_PNB: '10-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI10_USD_0_PNB_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_PHP_0_AGENCY: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_USD_0_AGENCY: '10-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI20_PHP_0_PNB: '20-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI20_PHP_0_PNB_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_USD_0_PNB: '20-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI20_USD_0_PNB_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_USD_0_HSBC_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_PHP_0_PNB: 'Term to Age 65 Waiver of Premium due to CI and TPD',
    UL_WPCI65_PHP_0_PNB_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_PHP_0_AGENCY: 'Term to Age 65 Waiver of Premium due to CI and TPD',
    UL_WPCI65_PHP_0_AGENCY_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_USD_0_PNB: 'Term to Age 65 Waiver of Premium due to CI and TPD',
    UL_WPCI65_USD_0_PNB_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_USD_0_AGENCY: 'Term to Age 65 Waiver of Premium due to CI and TPD',
    UL_WPCI65_USD_0_AGENCY_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_WPCI05_PHP_0_AGENCY: '5-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI05_USD_0_AGENCY: '5-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI20_PHP_0_AGENCY: '20-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI20_USD_0_AGENCY: '20-Yr. Waiver of Premium due to CI and TPD',
    UL_WPCI05_PHP_0_AGENCY_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI05_USD_0_AGENCY_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_PHP_0_AGENCY_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_USD_0_AGENCY_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_PHP_0_AGENCY_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_USD_0_AGENCY_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI05_PHP_0_WST_LTG_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI05_USD_0_WST_LTG_AZ: '5-Pay, 5-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_PHP_0_WST_LTG_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI10_USD_0_WST_LTG_AZ: '10-Pay, 10-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_PHP_0_WST_LTG_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI20_USD_0_WST_LTG_AZ: '20-Pay, 20-Year Term Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_PHP_0_WST_LTG_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_WPCI65_USD_0_WST_LTG_AZ: 'Pay-to-Age 65, Term-to-Age 65 Waiver of Premium Rider due to CI and TPD',
    UL_COLA3_PHP_0_AGENCY: 'COLA 3%',
    UL_COLA3_USD_0_AGENCY: 'COLA 3%',
    UL_COLA5_PHP_0_AGENCY: 'COLA 5%',
    UL_COLA5_USD_0_AGENCY: 'COLA 5%',
    UL_COLA10_PHP_0_AGENCY: 'COLA 10%',
    UL_COLA10_USD_0_AGENCY: 'COLA 10%',
    UL_COLA3_PHP_0_HSBC: 'COLA 3%',
    UL_COLA3_USD_0_HSBC: 'COLA 3%',
    UL_COLA5_PHP_0_HSBC: 'COLA 5%',
    UL_COLA5_USD_0_HSBC: 'COLA 5%',
    UL_COLA10_USD_0_HSBC: 'COLA 10%',
    UL_COLA3_PHP_0_PNB: 'COLA 3%',
    UL_COLA3_USD_0_PNB: 'COLA 3%',
    UL_COLA5_PHP_0_PNB: 'COLA 5%',
    UL_COLA5_USD_0_PNB: 'COLA 5%',
    UL_COLA10_PHP_0_PNB: 'COLA 10%',
    UL_COLA10_USD_0_PNB: 'COLA 10%',
    UL_COLA3_PHP_0_WST_LTG: 'COLA 3%',
    UL_COLA3_USD_0_WST_LTG: 'COLA 3%',
    UL_COLA5_PHP_0_WST_LTG: 'COLA 5%',
    UL_COLA5_USD_0_WST_LTG: 'COLA 5%',
    UL_COLA10_PHP_0_WST_LTG: 'COLA 10%',
    UL_COLA10_PHP_0_HSBC: 'COLA 10%',
    UL_COLA10_USD_0_WST_LTG: 'COLA 10%',
    UL_PBR_PHP_0_AGENCY: 'Regular PBR',
    UL_PBR_USD_0_AGENCY: 'Regular PBR',
    UL_PBR5_PHP_0_AGENCY: '5-Year PBR',
    UL_PBR5_USD_0_AGENCY: '5-Year PBR',
    UL_PBR10_PHP_0_AGENCY: '10-Year PBR',
    UL_PBR10_USD_0_AGENCY: '10-Year PBR',
    TR_SPR_WWF_PHP_0_PNB: 'World Wildlife Fund (Food Shed Program)',
    TR_APR_PHP_0_PNB: 'Accident Protect Rider',
    UL_PBR_PHP_0_PNB: 'Regular PBR',
    UL_PBR_USD_0_PNB: 'Regular PBR',
    UL_PBR5_PHP_0_PNB: '5-Year PBR',
    UL_PBR5_USD_0_PNB: '5-Year PBR',
    UL_PBR10_PHP_0_PNB: '10-Year PBR',
    UL_PBR10_USD_0_PNB: '10-Year PBR',
    UL_ESSENTIAL_1000_PHP_0_AGENCY: 'Essential Care(Semi Private)',
    UL_ESSENTIAL_2500_PHP_0_AGENCY: 'Essential Care(Private)',
    UL_ESSENTIAL_5000_PHP_0_AGENCY: 'Essential Care(Suite)',
    UL_ESSENTIAL_500_PHP_0_AGENCY: 'Essential Care(Ward)',
    UL_ESSENTIAL_PLUS_1000_PHP_0_AGENCY: 'Essential Care Plus(Semi Private)',    
    UL_ESSENTIAL_PLUS_2500_PHP_0_AGENCY: 'Essential Care Plus(Private)',
    UL_ESSENTIAL_PLUS_5000_PHP_0_AGENCY: 'Essential Care Plus(Suite)',
    UL_ESSENTIAL_PLUS_500_PHP_0_AGENCY: 'Essential Care Plus(Ward)',
};
