export const ACTION_MESSAGE = {
  LEAVE_PAGE: 'Are you sure you want to leave this page?',
  SAVE_CHANGES: 'Are you sure you want to save your changes?',
  DETECT_ADDR_CHANGES: 'We detect some updates in the information provided from Leads. Are you sure you want to save your changes?',
  NO_REFERROR_SET: 'You did not set any referror. Do you still want to continue?',
  DELETE_LEAD: 'Are you sure you want to delete this Lead? Deleting this record will remove\
  all records related to this Lead (NA, IRPQ, SI and Application Form).',
  DELETE_NEED: 'Are you sure you want to delete this Record?',
  FNA_NOT_COMPLETE: 'Please Complete Need Analysis to create IRPQ.',
  DELETE_ATTACHED_NEED: 'Cannot delete an attached/submitted FNA record.',
  EDIT_ATTACHED_NEED: 'Sorry, but you can\'t edit an attached FNA record',
  NO_FNA: 'Please Complete Need Analysis to create IRPQ.',
  EDIT_IRPQ: 'Editing IRPQ will change the IRPQ Status from COMPLETE to IN-PROGRESS',
  DELETE_IRPQ: 'Are you sure you want to delete this IRPQ?',
  SUCCESS_DELETE_IRPQ: 'Successfully deleted IRPQ record.',
  CANNOT_DELETE_IRPQ: 'Cannot delete an attached / submitted IRPQ.',
  DELETE_IMAGE: 'Are you sure you want to delete this attachment?',
  DELETE_PAYMENT: 'Switching to Online Payment will remove your currently attached Proof of Payment and Reference Number. Do you want to proceed?',
  SWITCH_CREDIT_CARD: 'Switching this button will remove your currently saved data. Do you want to proceed?',
  DELETE_SI: 'Are you sure you want to delete this Sales Illustration?',
  CANNOT_DELETE_SI: 'Cannot delete an attached / submitted Sales Illustration.',
  LEAD_EXISTS: 'Lead record already exists. Do you want to view the lead record?',
  MUST_COMPLETED_NA: 'Please create a Needs Analysis to continue.',
  MUST_COMPLETED_NA_IRPQ: 'Please Complete Need Analysis to create IRPQ.',
  MUST_COMPLETED_SI: 'Please create a Sales Illustration with a status of COMPLETED to continue',
  EDIT_COMPLETED_SI: 'Editing a Completed Sales Illustration will change the status to In-Progress. Do you want to proceed?',
  PAYMENT_OFFLINE: 'You must be connected to the internet in order to make this action.',
  PAYMENT_STATUS_UPDATED: 'Payment status updated.',
  PAYMENT_STATUS_UPDATED_FAILED: 'Payment status update failed.',
  FNA_EMAIL_OFFLINE: 'Sorry, but you cannot email your NA while you are offline.',
  SI_EMAIL_OFFLINE: 'Sorry, but you cannot email your SI while you are offline.',
  IRPQ_EMAIL_OFFLINE: 'Email functionality works only when the device is online.',
  EMAIL_ERROR: 'Email Error',
  SEND_EMAIL: 'Please wait, attempting to send email...',
  FNA_NOT_SYNCED: 'Need analysis has not yet synced with server',
  SI_NOT_SYNCED: 'Sales Illustration has not yet synced with server',
  IRPQ_NOT_SYNCED: 'IRPQ has not yet synced with server',
  FNA_LEAD_NO_EMAIL: 'Please update Email details for selected lead.',
  CANNOT_ATTACH_POP: 'Cannot complete this action. Payment has already been made.',
  SWITCH_TO_ATTACH_POP: 'Are you sure you want to attach your Proof of Payment instead?',
  ATTACHMENT_DISCLAIMER: `For the intermediaries: By clicking the agree button, you are taking the responsibility in ensuring the validity of the IDs
  and documents you are capturing`,
  NO_CONNECTION_EPAYMENT: 'Please connect to the Internet to pay online.',
  CANNOT_PAY_ONLINE: 'Cannot complete action. The application is already submitted.',
  CANCELLED_PAYMENT_ATTEMPT: 'The payment attempt was cancelled last <br> #datetime#. Please try again.',
  UNSUCCESSFUL_PAYMENT_ATTEMPT: 'The payment attempt was unsuccessful last <br> #datetime#. Please try again.',
  SUCCESSFUL_PAYMENT_ATTEMPT: 'Thank you! Your Payment was successful.',
  SUBMISSION_SUCCESS_OFFLINE: 'Application stored successfully. Application shall be submitted once user goes online.',
  DELETE_EAPP: 'Are you sure you want to delete this E-Application?',
  PREVIOUS_PAGE_RESET: 'Updating the values in the previous screen will reset the values in the succeeding screens',
  SI_AGE_NOT_UPDATED: 'Current age of Proposed Insured is no longer the same with age in SI. Please regenerate SI before creating an application.',
  SI_BMI_LIMIT: 'BMI of the Proposed Insured has exceeded max limit of 32. Plan is not applicable.',
  SI_BMI_LIMIT_BUSS: 'Resulting BMI is not within the acceptable range.',
  ONLINE_PAYMENT_DISABLED: 'Online Payment is disabled.',
  SI_DECLARATIONS_HEALTH_ISSUE: 'One of the questions has been found with a “YES” response. Plan is not applicable.',
  SI_DECLARATIONS_HEALTH_ISSUE_BUSS: 'One of the questions has been found with a “YES” response. Insured is not qualified for the plan.',
  EPAYMENT_RESTRICTED: 'Pay Online is not available for plan selected.',
  LIMIT_REFERROR: 'To update referrer, please delete the saved record and create a new one.',
  EPAYMENT_ELIGIBLE_PAYOR: 'By proceeding with ePayments, the client certifies that he is an eligible payor.',
  CANNOT_ATTACH_IMAGE: 'Cannot attach image. Please try again.',
  FILE_NOT_SUPPORTED: 'The file that you are trying to upload is not supported. Journey only accepts PDF file type',
  IMAGE_NOT_SUPPORTED: 'The file that you are trying to upload is not supported. Journey only accepts JPEG and PNG image file types.',
  SIGN_PAGE_BACK: 'Leaving this page without proceeding to Submission Checklist will remove all of your changes. Would you like to continue?',
  DELETE_SUBMITTED_LEAD: 'Cannot delete this lead with associated application that was submitted.',
  DELETE_SUBMITTED_EAPP: 'Cannot delete a submitted E-Application',
  EDIT_EAPP: 'Any signatures and acknowledgements that have been provided in this application will be reset if you proceed to edit. Do you want to continue?',
  SUB_CHECK_BACK: 'You are about to leave Submission Checklist, do you want to leave and save your changes?',
  NEW_SYNC_CHANGE: 'Are you sure you want to change the sync process? This will delete all offline records in app. Will you proceed?',
  NO_LICENSE_DETECTED: 'No license detected. Please contact ITHelpdesk.',
  NO_VALIDITY_TRAD: 'There is a missing date in your License Validity for Traditional License. Kindly reach out to Licensing through Journey Support. Once notified that this has been resolved, kindly connect to the internet and click on refresh to sync Journey with the latest updates',
  NO_VALIDITY_UL: 'There is a missing date in your License Validity for Variable Life License. Kindly reach out to Licensing through Journey Support. Once notified that this has been resolved, kindly connect to the internet and click on refresh to sync Journey with the latest updates',
  NO_REFERRER_DETAILS: 'Are you sure you want to continue without Referrer Details?',
  AGE_ISSUE_BUSS: 'Age does not qualify. Owner’s age nearest birthday has to be 18 to 55 years old.',
  AGE_ISSUE_AFC: 'Age does not qualify.'
}