export const MESSAGE = {
  GET_SYNC_TIME: 'Getting Sync Time..',
  GET_SYNC_SETTINGS: 'Getting Sync Settings...',
  ACCEPT_AGREEMENT: 'Accepting User Agreement...',
  ACCOUNT_MANAGER: 'Getting Account Manager Details...',
  ONLINE_LOGIN: 'Performing Online Login...',
  PASSWORD_REQUIRED: 'Password is Required.',
  RESET_PASSWORD: 'Reset Password...',
  RESET_PASSWORD_INFO: 'To reset password, the device must be connected to network. Please connect to network to reset password.',
  INVALID_TEMP_PASSWORD: 'Temporary password is invalid.',
  ENTER_TEMP_PASSWORD: 'Please enter your temporary password.',
  ENTER_NEW_PASSWORD: 'Please enter a new password.',
  PASSWORD_NOT_MATCH: 'Passwords do not match.',
  PASSWORD_NOT_MEET: 'Entered password does not meet the requirements.',
  PASSWORD_CHANGED: 'Password has been changed.',
  PASSWORD_RESET_REQUEST_UNAUTHORIZED: "Organization only allows resetting of password once per day. Please contact IT.Helpdesk@allianzpnblife.ph",
  PASSWORD_RESET_REQUEST_ERROR: "Server error encountered. Please try again and if issue still persists, please contact IT.Helpdesk@allianzpnblife.ph.",
  PASSWORD_RESET_REQUEST_TIMEOUT: "Server timeout encountered. Please try again and if issue still persists, you may contact IT.Helpdesk@allianzpnblife.ph.",
  PASSWORD_RESET_REQUEST_WENT_WRONG: "Something went wrong. Please try again and if issue still persists, please contact IT.Helpdesk@allianzpnblife.ph.",
  UNABLE_TO_PROCESS: 'Unable to proccess your request now. Please try again later',
  VALID_USERNAME: 'Please enter a valid username.',
  ENTER_USERNAME: 'Enter Username',
  OUTDATED_USERNAME: 'Account is not updated. Please contact IT Helpdesk at (02) 555-4911 or IT.Helpdesk@allianzpnblife.ph for assistance.',
  FIRST_LOGIN_CONNECTION: 'First time login requires internet connection, please connect to the internet to proceed.',
  PASSWORD_HAS_RESET: 'Your password has been reset, please connect the device to network to attempt online login.',
  ACCOUNT_LOCKED: 'Your account has been locked or disabled, please contact IT Helpdesk at (02) 555-4911 or IT.Helpdesk@allianzpnblife.ph for assistance.',
  REQUEST_PROBLEM: 'We have encountered problems completing your request, please try again',
  NO_CREDENTIALS: 'Please enter your credentials.',
  INVALID_OFFLINE_CREDENTIALS: 'Sorry, your password is incorrect.',
  ERROR_GENERIC: 'Sorry. Something went wrong. Please try again later.',
  ERROR_SQL_INITIALIZATION: 'SQLite database is not initialized yet.',
  ERROR_SEVEN_DAYS: 'You have been offline for 7 days, please connect to the internet and login to continue using the system.',
  OFFLINE_LOGIN_SUCCESS: 'Successful Offline Login!',
  EXCEEDED_INVALID_OFFLINE_LOGINS: 'Your account has been locked or disabled, please connect to the internet and try logging in again.',
  GENERATING_PDF: 'Generating PDF...',
  LOADING: 'Loading..',
  TRAD_PRODUCTS_ONLY: 'Since there is no IRPQ, only Traditional products will be available',
  UL_PRODUCT_NO_IRPQ: 'Since there is no IRPQ, cannot select Unit Linked Products.',
  ERROR_INCOMPLETE: 'Please check all necessary fields!',
  REGULAR_TOPUP: 'Regular Top Up minimum value of 10,000',
  FUND_ALLOCATION: 'Fund allocation should be equal to 100%!',
  NAVPU_DATE_MESSAGE: 'As of November 04, 2021',
  NO_TOPUP_WITHDRAWAL: 'Please add Policy year, Top Up or Withdrawal.',
  ERROR_NO_NETWORK: 'Sorry, but you must be connected to the internet before you are able to proceed.',
  NO_FNA_ON_CREATE_SI: 'Please Complete Need Analysis to Create SI',
  NO_IRPQ_ON_CREATE_SI_AGENCY: 'Please Complete IRPQ to Create SI',
  FNA_WAIVED_VIEW: 'Sorry, but you cannot view an FNA waiver.',
  INVALID_CERTIFICATE: 'Sorry, your certificate appears to be invalid.',
  NO_ACCOUNTMANAGER_ID: 'Sorry, but it seems that we cannot get your account information as of the moment.',
  IDLE_TIME: 'You have been idle for 10 minutes. You will be automatically logged out in 30 seconds if you remain idle.\
  Unsaved changes will be lost. Click "OK" to resume session.',
  INVALID_FILE_FORMAT: 'Only JPG and PNG file formats are accepted. Please check your image before uploading.',
  WAIT: 'Please wait...',
  SUBMIT_FORM: 'Submitting forms...',
  INVALID_TABS:  'Some tabs are invalid. Please check before submitting',
  NO_MOBILE_CONNECTION: 'No Internet Connection. Please check your internet connection.',
  ERROR_DATA: 'SYNCED ERROR',
  SYNCED_DATA: 'SYNCED DATA',
  SYNCING: 'Syncing data',
  CHECKLIST_DELTA_SYNC: 'Checklist Delta Sync',
  CHECKLIST_UNSYNC: 'Getting Checklist Unsync Data',
  CHECKLIST_EAPP_DETAILS: 'Getting EAPP Details',
  CHECKLIST_SUBMISSION_PAYMENT: 'Getting Submission Payment by submission ID',
  CHECKLIST_SIGNATURES: 'Getting Attached Signatures',
  CHECKLIST_EAPP_PERSON_DETAILS: 'Getting EAPP Person Details',
  CHECKLIST_SI_PERSON: 'Getting SI Person',
  CHECKLIST_DELTA_RESPONSE: 'Getting Delta Sync Response',
  CHECKLIST_UPDATING_STATUS: 'Updating record status',
  CHECKLIST_SYNCING_ATTACHMENT: 'Syncing attachments',
  CHECKLIST_INITIATE_UPDATE: 'Initiating Update Checklist',
  CHECKLIST_CHECK_DOCUMENTS: 'Checking documents',
  CHECKLIST_INITIATE_UPDATE_PAYMENT: 'Initiating Update Submission Payment',
  CHECKLIST_INITIATE_UPDATE_SUBMISSION_ID: 'Initiating Update Submission ID detail handler',
  CHECKLIST_INITIATE_UPDATE_SUBMISSION_DATA: 'Initiating Update Submission Checklist data',
  CHECKLIST_INITIATE_UPDATE_EAPP: 'Initiating Update EAPP',
  CHECKLIST_INITIATE_SINGLE_SUBMISSION: 'Initiating Single submission',
  CHECKLIST_FINALIZE_SUBMISSION: 'Finalizing Online Submission',
  INTERNET_NEEDED_TO_VIEW_FILE: 'Internet is needed to view this file',
  NETWORK_ERROR: "The connection to the server encountered a temporary error and could not complete your login request. Please try again in a few moments. If the problem persists, don't hesitate to contact IT.Helpdesk@allianzpnblife.ph.",
  EXPIRED_PASSWORD: 'Expired Password. Please contact IT.Helpdesk@allianzpnblife.ph',
  IS_LIFE_PLAN: 'Please select the type of plan',
  CONNECTION_TIMEOUT: "Internet connection timeout. Please try again.",
  APPLICATION_NUMBER_RESERVED_EMPTY: "No Remaining Application Number credits. <br/>Please connect to the internet and try again.",
  RETRY_SYNC_SI: "Syncing data, please wait...",
  ONLINE_PAYMENT_FAILED_EAPP_NOT_SYNC: 'Online payment failed: Check the EAPP is sync and please try again.',
  PLEASE_DONT_CLOSE_AFTER_UPDATE: `Please don't close Allianz Journey while your data is syncing to prevent data loss.`,
  ERROR_EMAIL: 'Sorry, something went wrong while sending the email.',
  NO_SELECTED_ROW: 'No selected row.'
} as const;
