export const PAYMENT_STATUS = {
    OFFLINE: 'OFFLINE',
    UNPAID: 'UNPAID',
    PAID: 'PAID',
    PENDING: 'PENDING',
    FAILED: 'FAILED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    SUCCESS: 'PAYMENT_SUCCESS',
    UNKNOWN: 'UNKNOWN',
}