export enum KEYS {
  BACKGROUND_SYNC = 'background_sync',
  CHECKLIST_ISSUBMITTED = 'checklist_issubmitted',
  LOCATION = 'location',
  NEW_SYNC = 'new_sync',
  OCCUPATIONS = 'occupations',
  SIGN_SUBMIT = 'sign_submit',
  SUBCHECK_SUBMIT = 'subcheck_submit',
  DS_ERRORS = 'DS_ERRORS',
  REFERROR = 'referror',
  OFF_APP_NUMBER = 'offline_application_number',
  OFF_APP_NUMBER_TRASH = 'offline_application_number_trash',
  OFF_APP_NUMBER_HISTORY = 'offline_application_number_history',
  DONTSHOWAGAIN_APP_NUMBER_ALERT = 'dontshowagain_app_number_alert',
  OFF_APP_NUMBER_API_ERROR_CODE = 'off_app_num_api_err_code',
  OFF_APP_FOR_REPLENISH = 'off_app_for_replenish',
  NA_RAW_DATA = 'na_raw_data',
  SIGNATURE_RAW_DATA = 'signature_raw_data',
  LATEST_APP_VERSION = 'latestAppVersion',
  SUBMITTED_APPLICATION_COUNT = 'SUBMITTED_APPLICATION_COUNT',
  EXPIRED_APPLICATION_COUNT = 'EXPIRED_APPLICATION_COUNT',
  UPDATED_JOURNEY_FIRST_LOGIN_ATTEMPT = 'UPDATED_JOURNEY_FIRST_LOGIN_ATTEMPT',
  INVALID_APPLICATION_NUMBER_HISTORY = 'INVALID_APPLICATION_NUMBER_HISTORY',
  APPLICATION_NUMBER_REFRESHED = 'APPLICATION_NUMBER_REFRESHED',
  ALL_APPLICATION_NUMBER_EAPP = 'ALL_APPLICATION_NUMBER_EAPP',
  LAST_APP_VERSION = 'LAST_APP_VERSION'
}
