export const SUBMISSION_QUERIES = {

    ACRMain: [
        { fieldName: 'pepClientName', formGroupControlName: 'pepClientName' },
        { fieldName: 'pepClientRole', formGroupControlName: 'pepClientRole' },
        { fieldName: 'pepName', formGroupControlName: 'pepName' },
        { fieldName: 'pepPosition', formGroupControlName: 'pepPosition' },
        { fieldName: 'pepRelationship', formGroupControlName: 'pepRelationship' },
        { fieldName: 'healthFactor', formGroupControlName: 'healthFactor' },
        { fieldName: 'healthFactorYes', formGroupControlName: 'healthFactorYes' },
        { fieldName: 'purpose', formGroupControlName: 'purpose' },
        { fieldName: 'purposeOthers', formGroupControlName: 'purposeOthers' },
        { fieldName: 'houseHoldAOIncome', formGroupControlName: 'houseHoldAOIncome' },
        { fieldName: 'houseHoldPIIncome', formGroupControlName: 'houseHoldPIIncome' },
        { fieldName: 'militaryMember', formGroupControlName: 'militaryMember' },
        { fieldName: 'militaryMemberYes', formGroupControlName: 'militaryMemberYes' },
        { fieldName: 'beenActive', formGroupControlName: 'beenActive' },
        { fieldName: 'beenActiveYes', formGroupControlName: 'beenActiveYes' },
        { fieldName: 'PEP', formGroupControlName: 'PEP' },
        { fieldName: 'remitAgent', formGroupControlName: 'remitAgent' },
        { fieldName: 'NGO', formGroupControlName: 'NGO' },
        { fieldName: 'casino', formGroupControlName: 'casino' },
        { fieldName: 'broker', formGroupControlName: 'broker' },
        { fieldName: 'jewelDealer', formGroupControlName: 'jewelDealer' },
        { fieldName: 'gunDealer', formGroupControlName: 'gunDealer' },
        { fieldName: 'validateIncome', formGroupControlName: 'validateIncome' },
        { fieldName: 'bankCert', formGroupControlName: 'bankCert' },
        { fieldName: 'bankPaySlip', formGroupControlName: 'bankPaySlip' },
        { fieldName: 'passbook', formGroupControlName: 'passbook' },
        { fieldName: 'incomeTax', formGroupControlName: 'incomeTax' },
        { fieldName: 'deedOfSale', formGroupControlName: 'deedOfSale' },
        { fieldName: 'sourceOfWealthOthers', formGroupControlName: 'sourceOfWealthOthers' },
        { fieldName: 'sourceOfWealthOthersYes', formGroupControlName: 'sourceOfWealthOthersYes' },
        { fieldName: 'netHouse', formGroupControlName: 'netHouse' },
        { fieldName: 'netHouseInput', formGroupControlName: 'netHouseInput' },
        { fieldName: 'netBusiness', formGroupControlName: 'netBusiness' },
        { fieldName: 'netBusinessInput', formGroupControlName: 'netBusinessInput' },
        { fieldName: 'netRealEstate', formGroupControlName: 'netRealEstate' },
        { fieldName: 'netRealEstateInput', formGroupControlName: 'netRealEstateInput' },
        { fieldName: 'assetsOthers', formGroupControlName: 'assetsOthers' },
        { fieldName: 'assetsOthersYes', formGroupControlName: 'assetsOthersYes' },
        { fieldName: 'salary', formGroupControlName: 'salary' },
        { fieldName: 'business', formGroupControlName: 'business' },
        { fieldName: 'gifts', formGroupControlName: 'gifts' },
        { fieldName: 'legalClaims', formGroupControlName: 'legalClaims' },
        { fieldName: 'investmentIncome', formGroupControlName: 'investmentIncome' },
        { fieldName: 'sourceOfFundOthers', formGroupControlName: 'sourceOfFundOthers' },
        { fieldName: 'sourceOfFundOthersYes', formGroupControlName: 'sourceOfFundOthersYes' },
        { fieldName: 'banking', formGroupControlName: 'banking' },
        { fieldName: 'manufacturing', formGroupControlName: 'manufacturing' },
        { fieldName: 'informationTech', formGroupControlName: 'informationTech' },
        { fieldName: 'pawnshop', formGroupControlName: 'pawnshop' },
        { fieldName: 'casinoOccupation', formGroupControlName: 'casinoOccupation' },
        { fieldName: 'governmentService', formGroupControlName: 'governmentService' },
        { fieldName: 'natureBusinessOthers', formGroupControlName: 'natureBusinessOthers' },
        { fieldName: 'natureBusinessOthersYes', formGroupControlName: 'natureBusinessOthersYes' },
        { fieldName: 'security', formGroupControlName: 'security' },
        { fieldName: 'protection', formGroupControlName: 'protection' },
        { fieldName: 'health', formGroupControlName: 'health' },
        { fieldName: 'education', formGroupControlName: 'education' },
        { fieldName: 'retirement', formGroupControlName: 'retirement' },
        { fieldName: 'estatePlanning', formGroupControlName: 'estatePlanning' },
        { fieldName: 'reasonOthers', formGroupControlName: 'reasonOthers' },
        { fieldName: 'reasonOthersYes', formGroupControlName: 'reasonOthersYes' },
        { fieldName: 'passport', formGroupControlName: 'passport' },
        { fieldName: 'NSO', formGroupControlName: 'NSO' },
        { fieldName: 'marriage', formGroupControlName: 'marriage' },
        { fieldName: 'confirmDobOthers', formGroupControlName: 'confirmDobOthers' },
        { fieldName: 'confirmDobOthersYes', formGroupControlName: 'confirmDobOthersYes' },
        { fieldName: 'bills', formGroupControlName: 'bills' },
        { fieldName: 'creditCard', formGroupControlName: 'creditCard' },
        { fieldName: 'onsite', formGroupControlName: 'onsite' },
        { fieldName: 'verifyAddressOthers', formGroupControlName: 'verifyAddressOthers' },
        { fieldName: 'verifyAddressOthersYes', formGroupControlName: 'verifyAddressOthersYes' },
        { fieldName: 'courtDecision', formGroupControlName: 'courtDecision' },
        { fieldName: 'courtResolution', formGroupControlName: 'courtResolution' },
        { fieldName: 'courtAffidavit', formGroupControlName: 'courtAffidavit' },
        { fieldName: 'clientCaseOthers', formGroupControlName: 'clientCaseOthers' },
        { fieldName: 'clientCaseOthersYes', formGroupControlName: 'clientCaseOthersYes' },
        { fieldName: 'isCompleted', formGroupControlName: 'isCompleted' }
    ],

    ADAMain: [
        { fieldName: 'bankName', formGroupControlName: 'bankName' },
        { fieldName: 'savings', formGroupControlName: 'savings' },
        { fieldName: 'isCompleted', formGroupControlName: 'isCompleted' },
    ],

    ACBMain: [
        { fieldName: 'cardType', formGroupControlName: 'cardType' },
        { fieldName: 'cardIssued', formGroupControlName: 'cardIssued' },
        { fieldName: 'cardAccount', formGroupControlName: 'cardAccount' },
        { fieldName: 'cardAddress1', formGroupControlName: 'cardAddress1' },
        { fieldName: 'cardAddress2', formGroupControlName: 'cardAddress2' },
        { fieldName: 'cardExpiry', formGroupControlName: 'cardExpiry' },
        { fieldName: 'isCompleted', formGroupControlName: 'isCompleted' },
    ]
};
